name: 'AppLambdaAction'
description: 'Deploy lambda with terraform'
inputs:
  app-name:
    description: 'Applcation id'
    default: ''
  suffix:
    description: 'Suffix for multi lambda in same repository'
    default: ''
  aws-role:
    description: 'Aws role to apply changes'
    default: ''
  terraform-version:
    description: 'Terraform version to install.'
    default: '1.9.7'
  terragrunt-version:
    description: 'Terragrunt version to install.'
    default: '0.68.1'
  terraform-app-lambda:
    description: 'terraform app lambda repository'
    default: 'FinalCAD/terraform-app-lambda'
  terraform-app-lambda-ref:
    descrition: 'Ref to use for pulling repo terraform-app-lambda'
    default: 'master'
  github-token:
    description: 'Github token to pull package to avoid limit rate'
    default: ''
  github-ssh:
    description: 'Github ssh key to pull terragrunt from github api'
    default: ''
  environment:
    description: 'Finalcad environment: production, staging, sandbox'
    default: ''
  region-friendly:
    description: 'Finalcad region: frankfurt or tokyo'
    default: 'frankfurt'
  sub-path:
    description: 'Subpath in current lambda repository'
    default: ''
  inject-route-files:
    description: 'Set to "true" in order to inject route files in to Lambda archive (only available for python_archive)'
    default: ''
  configuration-file:
    description: "Path to lambda configuration file"
    default: '.finalcad/lambda.yaml'
  policies-file:
    description: "Path to lambda policies file"
    default: '.finalcad/lambda-policies.json'
  pr-number:
    description: 'Pull rerquest number, empty fo push'
    default: ''
  python-version:
    description: 'Python version to construct python zip'
    default: '3.10'
  dry-run:
    description: 'Dry run'
    default: ''
  override-output-file:
    description: '(Optional) Path where to store override content from Terraform output.'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deprecated version of FinalCAD/AppLambdaAction
      shell: bash
      run: |
        echo '::error title=Deprecated version of FinalCAD/AppLambdaAction::This version of FinalCAD/AppLambdaAction is deprecated use `v1` instead.'
        exit 1
